name: CD/CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.5
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Install Xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Run tests with Xvfb
      run: xvfb-run -a pytest -vv --cov=src tests/test_*.py
    - name: Format code
      run: |
        make format